### ISSUE TITLE
关于神舟t97e

### ISSUE THREAD

**Issue by gangoogle** [cmbs2019/Mechrevo-Hackintosh#1]
哥们，我的t97e配置是8750h+1070 之前偶然找到你的老版本尽然可以兼用，我来试试你的新版本，另外能不能适配一下这个机器呢。。哈哈

**Comment by cmbs2019** [comment]
T97e似乎用的是老天的模具，可以hdmi输出独显的机型？

**Comment by gangoogle** [comment]
这就不太清楚了，不过确实是蓝天的模具

**Comment by gangoogle** [comment]
我装了你最新的z2 efi一点毛病没有。。。

**Comment by cmbs2019** [comment]
OK👌
